pmpserver/models.py
#! python3
# -*- coding: utf-8 -*-

from . import db
from sqlalchemy_utils import PasswordType

class User(db.Model):
    # Columns
    id = db.Column(db.String, primary_key=True)
    password = db.Column(
        PasswordType(
            schemes=['pbkdf2_sha512']
        ),
        nullable=False
    )

    email = db.Column(db.String)
    name = db.Column(db.String)
    role = db.Column(db.String)
    apikey = db.Column(db.String)
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        try:
            return unicode(self.id)  # python 2
        except NameError:
            return str(self.id)  # python 3

    def __repr__(self):
        return '<User %r email=%s>' % (self.id, self.email)


class DataDictionary(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True)
    definition = db.Column(db.String)

    def __repr__(self):
        return '<Data %s = %s>' % (self.id, self.definition)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post %r>' % (self.body)

pmpserver/admin/forms.py
#! python3
# -*- coding: utf-8 -*-

from ..forms import ModelForm
from ..models import User

class UserEditForm(ModelForm):
    class Meta:
        model = User
        exclude = ['password']

class UserEntryForm(ModelForm):
    class Meta:
        model = User
        include = ['id']

pmpserver/datadictionary/forms.py
#! python3
# -*- coding: utf-8 -*-

#from flask.ext.wtf import Form
#from wtforms.validators import Required

from ..forms import ModelForm
from ..models import DataDictionary

class DataDictionaryEditForm(ModelForm):
    class Meta:
        model = DataDictionary
        include = ['name']

class DataDictionaryEntryForm(ModelForm):
    class Meta:
        model = DataDictionary
        include = ['name']

pmpserver/forms.py
#! python3
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms_alchemy import model_form_factory
from . import db

BaseModelForm = model_form_factory(Form)

class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session

pmpserver/login/forms.py
#! python3
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms.fields import TextField, PasswordField
from wtforms import BooleanField
from wtforms.validators import Required

class LoginForm(Form):
    id = TextField('id', validators=[Required()])
    password = PasswordField('Password', validators=[Required('パスワードが入力されていません。')])
    remember_me = BooleanField('remember_me', default=False)

pmpserver/userprofile/forms.py
#! python3
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms.validators import Required
from wtforms.fields import PasswordField

class ChangePasswordForm(Form):
    old_password = PasswordField('古いパスワード', validators=[Required('新しいパスワードが入力されていません。')])
    new_password = PasswordField('新しいワスワード', validators=[Required('古いパスワードが入力されていません。')])

pmpserver/__init__.py
#! python3
# -*- coding: utf-8 -*-

import os
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.principal import Principal, Permission, RoleNeed

#create flask application
app = Flask(__name__, instance_relative_config=True)
app.config.from_object('config')
app.config.from_pyfile('config.py')

db = SQLAlchemy(app)

lm = LoginManager()
lm.init_app(app)

principals = Principal(app)

from pmpserver import views, models

from . import login
app.register_blueprint(login.app)

from . import admin
app.register_blueprint(admin.app, url_prefix="/admin")

from . import userprofile
app.register_blueprint(userprofile.app, url_prefix="/userprofile")

from . import datadictionary
app.register_blueprint(datadictionary.app, url_prefix="/datadictionary")

if __name__ == '__main__':
    manager.run()

pmpserver/admin/__init__.py
#! python3
# -*- coding: utf-8 -*-

from flask import Blueprint

app = Blueprint(
    'admin',
    __name__,
    template_folder='templates',
    #static_folder='static'
)

from . import views

pmpserver/admin/views.py
#! python3
# -*- coding: utf-8 -*-

#from flask import Flask, Response, current_app, g, request, session
from flask import request
from flask import render_template, flash, redirect, url_for
from flask.ext.principal import Permission, RoleNeed
from .. import db
from ..models import User
from .forms import UserEntryForm, UserEditForm
from . import app

#-------------------------------------------------------------------------------
# Permission
#-------------------------------------------------------------------------------
# Create a permission with a single Need, in this case a RoleNeed.
admin_permission = Permission(RoleNeed('admin'))

#-------------------------------------------------------------------------------
# for user management
#-------------------------------------------------------------------------------
@app.route('/users.html')
@admin_permission.require()
def users():
    return render_template('/users.html', users=User.query.all())

@app.route('/edit_user/<userid>', methods=['GET', 'POST'])
def edit_user(userid):
    user = User.query.get_or_404(userid)
    form = UserEditForm(request.form, user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.commit()
    return render_template('edituser.html', form=form, user=user)

@app.route('/add_user', methods=['GET', 'POST'])
@admin_permission.require()
def add_user():
    form = UserEntryForm(request.form)
    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        flash('New user was successfully posted')
        return redirect(url_for('.add_user'))
    return render_template('adduser.html', form=form)

@app.route('/delete_user/<userid>')
@admin_permission.require()
def delete_user(userid):
    user = User.query.get_or_404(userid)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('.users'))

@app.route('/password_reset/<userid>')
@admin_permission.require()
def password_reset(userid):
    user = User.query.get_or_404(userid)
    user.password = user.id
    db.session.commit()
    flash("<%s>'s password was successfully reset to the same as the user id." % user.id)
    return redirect(url_for('.users'))

pmpserver/datadictionary/__init__.py
#! python3
# -*- coding: utf-8 -*-

from flask import Blueprint

app = Blueprint(
    'datadictionary',
    __name__,
    template_folder='templates',
    #static_folder='static'
)

from . import views

pmpserver/datadictionary/views.py
#! python3
# -*- coding: utf-8 -*-

from flask import request
from flask import render_template, flash, redirect, abort, url_for
from flask.ext.principal import Permission, UserNeed
from .. import db
from ..models import DataDictionary
from .forms import DataDictionaryEditForm, DataDictionaryEntryForm
from . import app

@app.route('/entries.html')
def entries():
    return render_template('/entries.html', entries=DataDictionary.query.all())

@app.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    entry = DataDictionary.query.get_or_404(id)
    form = DataDictionaryEditForm(request.form, entry)
    if form.validate_on_submit():
        form.populate_obj(entry)
        db.session.commit()
    return render_template('edit.html', form=form, entry=entry)

@app.route('/add', methods=['GET', 'POST'])
def add():
    form = DataDictionaryEntryForm(request.form)
    if form.validate_on_submit():
        entry = DataDictionary()
        form.populate_obj(entry)
        db.session.add(entry)
        db.session.commit()
        flash('New entry was successfully posted')
        return redirect(url_for('.add'))
    return render_template('add.html', form=form)

@app.route('/delete/<id>')
def delete(id):
    entry = DataDictionary.query.get_or_404(id)
    db.session.delete(entry)
    db.session.commit()
    return redirect(url_for('.entries'))

pmpserver/login/__init__.py
#! python3
# -*- coding: utf-8 -*-

from flask import Blueprint

app = Blueprint(
    'login',
    __name__,
    template_folder='templates'
)

from . import views

pmpserver/login/views.py
#! python3
# -*- coding: utf-8 -*-

from flask import current_app, request
from flask import render_template, flash, redirect, url_for
from flask.ext.login import login_user, logout_user, current_user, login_required
from flask.ext.principal import Identity, identity_loaded, identity_changed
from flask.ext.principal import RoleNeed, UserNeed

from .. import app as App
from .. import lm
from ..models import User
from .forms import LoginForm

from . import app

#-------------------------------------------------------------------------------
# for Login Manager / User Information Provider
#-------------------------------------------------------------------------------

@lm.user_loader
def load_user(id):
    return User.query.get(id)

lm.login_view = 'login.login'
lm.login_message = u"ようこそここへクッククック"

@app.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('index'))
    error = None
    form = LoginForm()
    if form.validate_on_submit():
        user = load_user(form.id.data)
        if (user is not None) and (form.password.data == user.password):
            login_user(user, remember=form.remember_me.data)
            # Tell Flask-Principal the identity changed
            identity_changed.send(current_app._get_current_object(),
                                  identity=Identity(user.id))
            flash('You were logged in')
            return redirect(request.args.get('next') or url_for('index'))
        error = 'Invalid id or password'
    return render_template('login.html', form=form, error=error)

@app.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out')
    return redirect(url_for('index'))

#-------------------------------------------------------------------------------
# for User Information
#-------------------------------------------------------------------------------
@identity_loaded.connect_via(App)
def on_identity_loaded(sender, identity):
    # Set the identity user object
    identity.user = current_user

    # Add the UserNeed to the identity
    if hasattr(current_user, 'id'):
        identity.provides.add(UserNeed(current_user.id))

    # Assuming the User model has a list of roles, update the
    # identity with the roles that the user provides
    if hasattr(current_user, 'roles'):
        for role in current_user.roles:
            identity.provides.add(RoleNeed(role.name))
    if hasattr(current_user, 'role'):
        identity.provides.add(RoleNeed(current_user.role))

pmpserver/userprofile/__init__.py
#! python3
# -*- coding: utf-8 -*-

from flask import Blueprint

app = Blueprint(
    'userprofile',
    __name__,
    template_folder='templates',
    #static_folder='static'
)

from . import views

pmpserver/userprofile/views.py
#! python3
# -*- coding: utf-8 -*-

from flask import request
from flask import render_template, flash, redirect, abort
from flask.ext.principal import Permission, UserNeed
from .. import db
from ..models import User
from .forms import ChangePasswordForm
from . import app

class ChangePasswordPermission(Permission):
    def __init__(self, userid):
        need = UserNeed(userid)
        super(ChangePasswordPermission, self).__init__(need)

@app.route('/change_password/<userid>', methods=['GET', 'POST'])
def change_password(userid):
    permission = ChangePasswordPermission(userid)
    if not permission.can():
        abort(403)  # HTTP Forbidden

    user = User.query.get_or_404(userid)
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        if user.password != form.old_password.data:
            flash("Invalid password.")
        else:
            user.password = form.new_password.data
            db.session.commit()
            flash("<%s>'s password was successfully changed." % user.id)
    return render_template('change_password.html', form=form, user=user)

pmpserver/util/__init__.py
#! python3
# -*- coding: utf-8 -*-

pmpserver/views.py
#! python3
# -*- coding: utf-8 -*-

import os
import json
import sqlite3
from contextlib import closing
from datetime import datetime
from flask import Flask, Response, current_app, g, request, session
from flask import render_template, flash, redirect, url_for, abort

from . import app

#-------------------------------------------------------------------------------
# for database
#-------------------------------------------------------------------------------

def projectsdir():
    return os.path.join(os.path.dirname(os.path.dirname(__file__)), 'instance', 'projects')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/install.html')
def install():
    return render_template('install.html')

@app.route('/apikey.html')
def show_apikey():
    if 'logged_in' in session and session['logged_in'] == True:
        return render_template('apikey.html')
    else:
        return redirect(url_for('login.login'))
        #return render_template('login.html', error='APIキーを表示するにはログインしてください')

@app.route('/project_list.html')
def project_list():
    path = projectsdir()
    files = [x for x in os.listdir(path) if os.path.isdir(os.path.join(path, x))]
    return render_template('projects.html', projects=files)

#handle http request(Web API)
@app.route('/pmp/api/projects/')
def api_project_list():
    return json.dumps(os.listdir(projectsdir()), ensure_ascii=False)

@app.route('/pmp/api/projects/<projectname>', methods=['GET', 'POST', 'PUT', 'DELETE'])
def api_projects(projectname):
    def _get_project(projectname):
        path = os.path.join(projectsdir(), projectname, 'current.json.txt')
        if not os.path.exists(path):
            return ('Not Found %s' % path, 404, [])
        return open(path, encoding='utf-8').read()
    #-------
    print('projectname=[%s]' % projectname)
    if request.method == 'GET':
        return _get_project(projectname)
    elif request.method == 'POST':
        #f = request.files['the_file']
        #f.save('/var/www/uploads/uploaded_file.txt')
        #print(request.args)
        #print(request.form)
        print(request.remote_addr, request.remote_user)
        _now = datetime.now()
        path = os.path.join(projectsdir(), projectname, 'old',
            '%s_%s.txt' % (_now.strftime("%Y%m%d%H%M%S"), request.remote_addr))
        print(path)
        with open(path, "w", encoding='utf-8') as f:
            f.write(request.form['data'])
        return 'OK'
    else:
        path = os.path.join(projectsdir(), projectname, 'current.json.txt')
        if not os.path.exists(path):
            return ('Not Found %s' % path, 404, [])
        return open(path, encoding='utf-8').read()

pmpserver/templates/adduser.html
{% extends "base.html" %}
{% from 'field.html' import field_as_tr %}
{% block title %}ユーザ追加{% endblock %}
{% block header %}ユーザ追加{% endblock %}
{% block content %}
    <form action="{{ url_for('add_user') }}" method=post class=add-user>
      <table>
	{{ field_as_tr(form.id) }}
	{{ field_as_tr(form.password) }}
	{{ field_as_tr(form.email) }}
	{{ field_as_tr(form.name) }}
	{{ field_as_tr(form.role) }}
      </table>
      {{ form.csrf_token }}
      {{ form.hidden_tag() }}
      <input type=submit value="OK"/>
    </form>
{% endblock %}

pmpserver/templates/apikey.html
{% extends "base.html" %}
{% block title %}APIキー{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
        .important { color: #336699; }
    </style>
{% endblock %}
{% block header %}APIキー{% endblock %}
{% block content %}hogehoge{% endblock %}

pmpserver/templates/base.html
<!DOCTYPE html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    {% block head %}
    <link rel="stylesheet" href="/static/style.css" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>PMP - {% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
<div class=metanav>
    {% if current_user.is_authenticated() %}
        <p >ようこそ{{ current_user.name }}さん</p>
        <a href="{{ url_for('login.logout') }}">log out</a>
    {% else %}
        <a href="{{ url_for('login.login') }}">log in</a>
    {% endif %}
</div>
<div class=page>
    <div id="header">
        {% block header %}{% endblock %}
    </div>
    <div id="sidebar">
        <p>Table Of Contents</p>
        <div id="menu">
            {% block navi %}
            <ul>
                <li><a href="/">トップ</a></li>
                <li><a href="/install.html">インストール</a></li>
                <li><a href="/project_list.html">プロジェクト一覧</a></li>
                <li><a href="/apikey.html">APIキー</a></li>
                <li><a href="{{url_for('datadictionary.entries')}}">データ辞書</a></li>
                {% if current_user.is_authenticated() %}
                <li><a href="{{url_for('admin.users')}}">ユーザ一覧</a></li>
                <li><a href="{{url_for('userprofile.change_password', userid=current_user.id)}}">パスワード変更</a></li>
                {% endif %}
                {% block optionalmenu %}
                {% endblock %}
            </ul>
            {% endblock %}
        </div>
    </div>
    <div id="content">
        {% for message in get_flashed_messages() %}
        <div class=flash>{{ message }}</div>
        {% endfor %}
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</div>
</body>
</html>

pmpserver/templates/change_password.html
{% extends "base.html" %}
{% from 'field.html' import field_as_tr %}
{% block title %}ユーザ編集{% endblock %}
{% block header %}ユーザ編集{% endblock %}
{% block content %}
    <form action="{{ url_for('change_password', userid=user.id) }}" method=post class=edit-user>
      <table>
        <tr>
          <td>ID</td>
          <td>{{user.id}}</td>
	</tr>
	{{ field_as_tr(form.old_password) }}
	{{ field_as_tr(form.new_password) }}
      </table>
      {{ form.csrf_token }}
      {{ form.hidden_tag() }}
      <input type=submit value="更新"/>
    </form>
{% endblock %}

pmpserver/templates/edituser.html
{% extends "base.html" %}
{% from 'field.html' import field_as_tr %}
{% block title %}ユーザ編集{% endblock %}
{% block header %}ユーザ編集{% endblock %}
{% block content %}
    <form action="{{ url_for('edit_user', userid=user.id) }}" method=post class=edit-user>
      <table>
        <tr>
          <td>ID</td>
          <td>{{user.id}}</td>
	</tr>
	{{ field_as_tr(form.email) }}
	{{ field_as_tr(form.name) }}
	{{ field_as_tr(form.role) }}
      </table>
      {{ form.csrf_token }}
      {{ form.hidden_tag() }}
      <input type=submit value="更新"/>
    </form>
{% endblock %}

pmpserver/templates/field.html
{% macro field_as_tr(field) -%}
  <tr>
    <td>{{field.label}}</td>
    <td>{{field()}}</td>
    <td class=error>{{field.errors}}</td>
  </tr>
{%- endmacro %}


{% macro link_button(caption, url) -%}
  <button type="button" onclick="window.location.href='{{url}}'"><font size="2">{{caption}}</font></button>
{%- endmacro %}

pmpserver/templates/index.html
{% extends "base.html" %}
{% block title %}PMPのインストールと起動方法{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
        .important { color: #336699; }
    </style>
{% endblock %}
{% block header %}PMP{% endblock %}

pmpserver/templates/install.html
{% extends "base.html" %}
{% block title %}インストールと起動方法{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
        .important { color: #336699; }
    </style>
{% endblock %}
{% block header %}インストールと起動方法{% endblock %}
{% block content %}
    <style type="text/css"><!--
    .unavailable {
    text-decoration:line-through;
    }
    </style>
    <h2>【インストール】</h2>
    <p>次の手順でインストールしてください。</p>
    <p>１．Pythonをインストールする。</p>
        <ul>
        <li>Windows64bit用
            <ul>
            <li><a href="./static/downloads/64bit/python-3.3.5.amd64.msi">Python3.3インストーラ(64bit用)</a></li>
            </ul>
        </li>
        <li>Windows32bit用
            <ul>
            <li><a href="./static/downloads/32bit/python-3.3.5.msi">Python3.3インストーラ(32bit用)</a></li>
            <li><a href="./static/downloads/32bit/python-3.4.3.msi">Python3.4インストーラ(32bit用)</a></li>
            </ul>
        </li>
        </ul>
    <p>２．PyQtをインストールする。(Pythonのバージョンに合わせたものを選んでください)</p>
        <ul>
        <li>Windows64bit用
            <ul>
            <li><a href="./static/downloads/64bit/PyQt4-4.10.4-gpl-Py3.3-Qt4.8.6-x64.exe">PyQtインストーラ(Python3.3-64bit用)</a></li>
            </ul>
        </li>
        <li>Windows32bit用
            <ul>
            <li class=unavailable><a href="./static/downloads/32bit/PyQt4-4.11.3-gpl-Py3.3-Qt4.8.6-x32.exe">PyQtインストーラ(Python3.3-32bit用)</a></li>
            <li><a href="./static/downloads/32bit/PyQt4-4.11.3-gpl-Py3.4-Qt4.8.6-x32.exe">PyQtインストーラ(Python3.4-32bit用)</a></li>
            </ul>
        </li>
        </ul>
    <p>３．PMPモジュールのzipをダウンロードする。</p>
        <ul>
        <li><a href="./static/downloads/pmp-master.zip">PMPモジュール</a></li>
        </ul>
    <p>４．ダウンロードしたzipを任意のフォルダに解凍する。</p>
    <br/>

    <h2>【起動方法】</h2>
    <pre>
    方法１：
      解凍したzipの中にある、pmp.pywをダブルクリックしてください。
      (拡張子.pyw が、Python3と結びつけられていなければ動きません）

    方法２：
      ・解凍したzipのフォルダで、コマンドプロンプトを開きます。
      ・コマンドプロンプトで、"python pmp.pyw"を実行してください。
    </pre>
{% endblock %}
{% block footer %}
    {{ super() }}
{% endblock %}

pmpserver/templates/login.html
{% extends "base.html" %}
{% block title %}ログイン{% endblock %}
{% block head %}
    {{ super() }}
    <style type="text/css">
        .important { color: #336699; }
    </style>
{% endblock %}
{% block header %}ログイン{% endblock %}
{% block content %}
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('login') }}" method=post>
    <table>
       <tr><td>ID </td><td>{{ form.id() }}</td></tr>
       <tr><td>パスワード</td><td>{{ form.password() }}<td></tr>
       <tr><td>Remember Me</td><td>{{ form.remember_me }}<td></tr>
    </table>
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    <input type="submit" value="Login">
  </form>
{% endblock %}

pmpserver/templates/projects.html
{% extends "base.html" %}
{% block title %}プロジェクト一覧{% endblock %}
{% block header %}プロジェクト一覧{% endblock %}
{% block content %}
    <table border="1">
    <tr><th>プロジェクト略称</th><th>WBSデータ(JSON形式)のURL</th></tr>
    {% for project in projects %}
      <tr>
         <td><a href="{{ url_for('api_projects', projectname=project) }}">{{ project }}</a></td>
         <td>{{request.scheme}}://{{request.host}}{{ url_for('api_projects', projectname=project) }}</a></td>
      </tr>
    {% endfor %}
    </table>
    <p>このURLは、クライアントプログラムのサーバURLに設定してください。</p>
    <p>サーバURLは、[設定]-[オプション]メニューで、オプション設定ダイアログを開くか、
    settings.iniをテキストエディタで開いて、直接編集してください。</p>
    <p>サーバにアクセスできない場合、PROXY経由のアクセスになっている場合があります。</p>
    <p>その場合、HTTP_PROXY等の環境変数を削除するか、環境変数NO_PROXYに除外対象のサーバ名、IPアドレスを設定してください。</p>
    <pre>
    例）HTTP_PROXY=172.24.111.222:2000
    　　　 <-- こういう設定があるとPROXY経由になってしまうので、
        NO_PROXY=127.0.0.1, localhost, 172.24.160.99
    　　　 <-- PROXY経由にしたくないものを設定します。
    </pre>

{% endblock %}

pmpserver/templates/users.html
{% extends "base.html" %}
{% from 'field.html' import link_button %}

{% block title %}ユーザ一覧{% endblock %}
{% block header %}ユーザ一覧{% endblock %}
{% block optionalmenu %}
    {% if current_user.is_authenticated() %}
        <li><a href="/add_user">ユーザ追加</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <p>全{{users|length}}件：</p>
    <table border="1">
    <tr><th>ユーザＩＤ</th><th>ユーザ名</th><th>e-mail</th><th>ロール</th><th>操作</th></tr>
    {% for user in users %}
      <tr>
         <td>{{user.id}}</td>
         <td>{{user.name}}</td>
         <td>{{user.email}}</td>
         <td>{{user.role}}</td>
         <td>
            {{link_button('編集', url_for('edit_user', userid=user.id))}}
            {{link_button('削除', url_for('delete_user', userid=user.id))}}
            {{link_button('パスワードリセット', url_for('password_reset', userid=user.id))}}
         </td>
      </tr>
    {% endfor %}
    </table>
{% endblock %}